---
language: node_js
node_js:
  - '10'

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

install:
  - yarn install

script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test
